// App.tsx — AppShell version with FusionShell layout. Generated by scaffold-appshell.
import { useState, useCallback, useEffect } from 'react'
import { HashRouter, Routes, Route, Outlet, Navigate } from 'react-router-dom'
import { ThemeProvider } from '@design-systems/theme'
import ErrorBoundary from './ErrorBoundary'
import { FusionProvider } from './contexts/fusion'
import FusionShell from './components/FusionShell'
import { FUSION_CONFIG } from './navigation'
import { getConfig, applyTheme } from './config'
import OnboardingPage from './pages/OnboardingPage'
import ImportPage from './pages/ImportPage'
import AutomatedOnboardingPage from './pages/AutomatedOnboardingPage'
import DataReviewPage from './pages/DataReviewPage'
import DataReviewPopout from './pages/DataReviewPopout'
import SmartReturnPage from './pages/SmartReturnPage'
import CheckReturnPage from './pages/CheckReturnPage'
import ReturnInsightsPage from './pages/ReturnInsightsPage'
import WorkspacePage from './pages/WorkspacePage'
import HomePage from './pages/HomePage'
import NotFoundPage from './pages/NotFoundPage'

function AppLayout() {
  return (
    <FusionShell businessName={FUSION_CONFIG.businessName}>
      <Outlet />
    </FusionShell>
  )
}

// APP_PAGES — add new app page routes here (managed by /page skill)
const APP_PAGES: { path: string; component: React.ComponentType }[] = []

export default function App() {
  const [theme, setThemeState] = useState(() => getConfig()?.theme || 'intuit')

  const setTheme = useCallback((newTheme: string) => {
    setThemeState(newTheme)
    applyTheme(newTheme)
  }, [])

  useEffect(() => {
    applyTheme(theme)
  }, [theme])

  return (
    <ErrorBoundary>
      <ThemeProvider theme={theme} setTheme={setTheme}>
        <HashRouter>
          <FusionProvider pathPrefix={FUSION_CONFIG.pathPrefix || ''}>
            <Routes>
              <Route path="/onboarding" element={<OnboardingPage />} />
              <Route path="/import" element={<ImportPage />} />
              <Route path="/automated-onboarding" element={<AutomatedOnboardingPage />} />
              <Route path="/smart-return" element={<SmartReturnPage />} />
              <Route path="/check-return" element={<CheckReturnPage />} />
              <Route path="/check-return/insights" element={<ReturnInsightsPage />} />
              <Route path="/data-review" element={<DataReviewPage />} />
              <Route path="/data-review-popout" element={<DataReviewPopout />} />
              <Route element={<AppLayout />}>
                <Route path="/" element={<Navigate to="/home" replace />} />
                <Route path="/home" element={<HomePage />} />
                <Route path="/workspace" element={<WorkspacePage />} />
                {APP_PAGES.map(({ path, component: Page }) => (
                  <Route key={path} path={`/app/${path}`} element={<Page />} />
                ))}
                <Route path="/app/*" element={<NotFoundPage />} />
                <Route path="*" element={<NotFoundPage />} />
              </Route>
            </Routes>
          </FusionProvider>
        </HashRouter>
      </ThemeProvider>
    </ErrorBoundary>
  )
}
